//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_CONTRATO
    {
        public int ID_DETALLE_CONTRATO { get; set; }
        public int ID_CONTRATO { get; set; }
        public int ID_OFICIAL { get; set; }
        public decimal MONTO_OFICIAL { get; set; }
    
        public virtual TBL_CONTRATOS TBL_CONTRATOS { get; set; }
        public virtual TBL_OFICIALES TBL_OFICIALES { get; set; }

    }
}
