//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INVENTARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_INVENTARIO()
        {
            this.TBL_INVENTARIO_OFICIALES = new HashSet<TBL_INVENTARIO_OFICIALES>();
        }
    
        public int ID_INVENTARIO { get; set; }
        public string ARTICULO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> CANTIDAD_INICIAL { get; set; }
        public decimal CANTIDAD_ACTUAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_INVENTARIO_OFICIALES> TBL_INVENTARIO_OFICIALES { get; set; }
    }
}
