//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CONTRATOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CONTRATOS()
        {
            this.DETALLE_CONTRATO = new HashSet<DETALLE_CONTRATO>();
            this.DETALLE_CONTRATO1 = new HashSet<DETALLE_CONTRATO>();
        }
    
        public int ID_CONTRATO { get; set; }
        public Nullable<System.DateTime> FECHA_INICIAL { get; set; }
        public Nullable<System.DateTime> FECHA_FINAL { get; set; }
        public bool ESTADO_CONTRATO { get; set; }
        public decimal MONTO_TOTAL { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_CONTRATO> DETALLE_CONTRATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_CONTRATO> DETALLE_CONTRATO1 { get; set; }
        public virtual TBL_CLIENTES TBL_CLIENTES { get; set; }
        public virtual TBL_CLIENTES TBL_CLIENTES1 { get; set; }
        public virtual TBL_CLIENTES TBL_CLIENTES2 { get; set; }
        public virtual TBL_USUARIOS TBL_USUARIOS { get; set; }
        public virtual TBL_USUARIOS TBL_USUARIOS1 { get; set; }
        public virtual TBL_USUARIOS TBL_USUARIOS2 { get; set; }
    }
}
