//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_USUARIOS()
        {
            this.TBL_CONTRATOS = new HashSet<TBL_CONTRATOS>();
            this.TBL_CONTRATOS1 = new HashSet<TBL_CONTRATOS>();
            this.TBL_CONTRATOS2 = new HashSet<TBL_CONTRATOS>();
        }
    
        public int ID_Usuario { get; set; }
        public string identificacion { get; set; }
        public string Nombre_Usuario { get; set; }
        public string nombre_completo { get; set; }
        public string contrasena { get; set; }
        public Nullable<bool> estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CONTRATOS> TBL_CONTRATOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CONTRATOS> TBL_CONTRATOS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CONTRATOS> TBL_CONTRATOS2 { get; set; }
    }
}
