//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OFICIALES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_OFICIALES()
        {
            this.DETALLE_CONTRATO = new HashSet<DETALLE_CONTRATO>();
            this.DETALLE_CONTRATO1 = new HashSet<DETALLE_CONTRATO>();
            this.TBL_INVENTARIO_OFICIALES = new HashSet<TBL_INVENTARIO_OFICIALES>();
        }
    
        public int ID_OFICIAL { get; set; }
        public string CEDULA_OFICIAL { get; set; }
        public string NOMBRE_COMPLETO { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTEO { get; set; }
        public string RESIDENCIA { get; set; }
        public string TELEFONO { get; set; }
        public string CORREO { get; set; }
        public string GENERO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_CONTRATO> DETALLE_CONTRATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_CONTRATO> DETALLE_CONTRATO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_INVENTARIO_OFICIALES> TBL_INVENTARIO_OFICIALES { get; set; }
    }
}
